# Generated by Django 4.2.3 on 2023-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
