# Generated by Django 4.2.3 on 2023-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_register_degree_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application_area',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
