# Generated by Django 4.2.3 on 2023-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_project_application_area_project_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='components',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
