# Generated by Django 4.2.2 on 2023-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_project_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media/media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/media/'),
        ),
    ]
