# Generated by Django 4.2.2 on 2023-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_project_image_alter_project_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
